## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).



In [17]:
import numpy as np

# используем arange
N   = 10
arr = np.arange(N-1, -1, -1)
print(arr)

# с генератором 
print(np.array(range(N-1, -1, -1)))

# перевернём
print(np.array(range(0,N))[::-1])

[9 8 7 6 5 4 3 2 1 0]
[9 8 7 6 5 4 3 2 1 0]
[9 8 7 6 5 4 3 2 1 0]


## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.



In [40]:
N=10
m = np.diag(range(N,-1,-1))

print( 'diagonals sum: {}'.format(sum([m[i][i] for i in range(m.shape[0])])))
# матрица диагональная, можно просто всё проссумировать
print('Just sum: '+str(m.sum()))

diagonals sum: 55
Just sum: 55


## Задание 3
Решите систему уравнений:  
4x + 2y + z = 4  
x + 3y = 12  
5y + 4z = -3  

In [131]:
import numpy.linalg as linalg
# уравнение от 3ёх переменных
a = np.array([4, 2, 1,
              1, 3, 0,
              0, 5, 4]).reshape(3,3)
b = np.array([4, 12, -3]).astype(float)

x = linalg.solve(a, b)

print('Solution: {}'.format(x))

# проверим
bx = np.dot(a,x)
print(bx) # вроде да...
print(bx == b) # или нет?
print(bx[1]) # нет?
print(np.allclose( np.dot(a, x ), b)) # вроде таки да, с точностью 1е-8

Solution: [ 0.46666667  3.84444444 -5.55555556]
[ 4. 12. -3.]
[ True False  True]
11.999999999999998
True


In [117]:
np.dot(a,x).astype(int)

array([ 4, 11, -3])